version: '3.8'

services:
  ecoforeshubfrontend:
    build:
      context: ./ecoforesthub
    image: ecoforesthubfront
    container_name: ecoforeshubfront
    ports:
      - "9000:80"

  ecoforeshubserver:
    build: 
      context: ./apiecoforesthub
    image: fastapi_app
    container_name: fastapi_app
    restart: always
    ports:
      - "5000:80"
    environment:
      - DATABASE_URI=mysql://root:ecoforestsec@db:3306/ecoforesthub
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ecoforestsec
      MYSQL_DATABASE: ecoforesthub
    ports:
      - "3308:3306"
  

